/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as AppTrainerRouteImport } from './routes/app.trainer'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppMyFranchiseRouteImport } from './routes/app.my-franchise'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppFranchiseesRouteImport } from './routes/app.franchisees'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAcademyRouteImport } from './routes/app.academy'
import { Route as AppInventoryIndexRouteImport } from './routes/app.inventory.index'
import { Route as AppFinanceIndexRouteImport } from './routes/app.finance.index'
import { Route as AppAcademyIndexRouteImport } from './routes/app.academy.index'
import { Route as AppLeadsLeadIdRouteImport } from './routes/app.leads.$leadId'
import { Route as AppInventoryWarehousesRouteImport } from './routes/app.inventory.warehouses'
import { Route as AppInventorySuppliersRouteImport } from './routes/app.inventory.suppliers'
import { Route as AppInventoryStockRouteImport } from './routes/app.inventory.stock'
import { Route as AppInventoryPurchaseOrdersRouteImport } from './routes/app.inventory.purchase-orders'
import { Route as AppInventoryProductsRouteImport } from './routes/app.inventory.products'
import { Route as AppInventoryMovementsRouteImport } from './routes/app.inventory.movements'
import { Route as AppInventoryCategoriesRouteImport } from './routes/app.inventory.categories'
import { Route as AppFranchiseesFranchiseeIdRouteImport } from './routes/app.franchisees.$franchiseeId'
import { Route as AppFinanceRevenueRouteImport } from './routes/app.finance.revenue'
import { Route as AppFinancePayoutsRouteImport } from './routes/app.finance.payouts'
import { Route as AppFinanceExpensesRouteImport } from './routes/app.finance.expenses'
import { Route as AppFinanceCategoriesRouteImport } from './routes/app.finance.categories'
import { Route as AppAcademyTrainersRouteImport } from './routes/app.academy.trainers'
import { Route as AppAcademyStudentsRouteImport } from './routes/app.academy.students'
import { Route as AppAcademyFeesRouteImport } from './routes/app.academy.fees'
import { Route as AppAcademyCoursesRouteImport } from './routes/app.academy.courses'
import { Route as AppAcademyCertificatesRouteImport } from './routes/app.academy.certificates'
import { Route as AppAcademyBatchesRouteImport } from './routes/app.academy.batches'
import { Route as AppAcademyBatchesBatchIdRouteImport } from './routes/app.academy.batches.$batchId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainerRoute = AppTrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMyFranchiseRoute = AppMyFranchiseRouteImport.update({
  id: '/my-franchise',
  path: '/my-franchise',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppFranchiseesRoute = AppFranchiseesRouteImport.update({
  id: '/franchisees',
  path: '/franchisees',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademyRoute = AppAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppFinanceIndexRoute = AppFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppAcademyIndexRoute = AppAcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAcademyRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppInventoryWarehousesRoute = AppInventoryWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventorySuppliersRoute = AppInventorySuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryStockRoute = AppInventoryStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryPurchaseOrdersRoute =
  AppInventoryPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryProductsRoute = AppInventoryProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryMovementsRoute = AppInventoryMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryCategoriesRoute = AppInventoryCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppFranchiseesFranchiseeIdRoute =
  AppFranchiseesFranchiseeIdRouteImport.update({
    id: '/$franchiseeId',
    path: '/$franchiseeId',
    getParentRoute: () => AppFranchiseesRoute,
  } as any)
const AppFinanceRevenueRoute = AppFinanceRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinancePayoutsRoute = AppFinancePayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinanceExpensesRoute = AppFinanceExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinanceCategoriesRoute = AppFinanceCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppAcademyTrainersRoute = AppAcademyTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AppAcademyRoute,
} as any)
const AppAcademyStudentsRoute = AppAcademyStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppAcademyRoute,
} as any)
const AppAcademyFeesRoute = AppAcademyFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppAcademyRoute,
} as any)
const AppAcademyCoursesRoute = AppAcademyCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppAcademyRoute,
} as any)
const AppAcademyCertificatesRoute = AppAcademyCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppAcademyRoute,
} as any)
const AppAcademyBatchesRoute = AppAcademyBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AppAcademyRoute,
} as any)
const AppAcademyBatchesBatchIdRoute =
  AppAcademyBatchesBatchIdRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => AppAcademyBatchesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/academy': typeof AppAcademyRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRouteWithChildren
  '/app/franchisees': typeof AppFranchiseesRouteWithChildren
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/my-franchise': typeof AppMyFranchiseRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/trainer': typeof AppTrainerRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/app/': typeof AppIndexRoute
  '/app/academy/batches': typeof AppAcademyBatchesRouteWithChildren
  '/app/academy/certificates': typeof AppAcademyCertificatesRoute
  '/app/academy/courses': typeof AppAcademyCoursesRoute
  '/app/academy/fees': typeof AppAcademyFeesRoute
  '/app/academy/students': typeof AppAcademyStudentsRoute
  '/app/academy/trainers': typeof AppAcademyTrainersRoute
  '/app/finance/categories': typeof AppFinanceCategoriesRoute
  '/app/finance/expenses': typeof AppFinanceExpensesRoute
  '/app/finance/payouts': typeof AppFinancePayoutsRoute
  '/app/finance/revenue': typeof AppFinanceRevenueRoute
  '/app/franchisees/$franchiseeId': typeof AppFranchiseesFranchiseeIdRoute
  '/app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/app/inventory/movements': typeof AppInventoryMovementsRoute
  '/app/inventory/products': typeof AppInventoryProductsRoute
  '/app/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/app/inventory/stock': typeof AppInventoryStockRoute
  '/app/inventory/suppliers': typeof AppInventorySuppliersRoute
  '/app/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/academy/': typeof AppAcademyIndexRoute
  '/app/finance/': typeof AppFinanceIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/academy/batches/$batchId': typeof AppAcademyBatchesBatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/franchisees': typeof AppFranchiseesRouteWithChildren
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/my-franchise': typeof AppMyFranchiseRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/trainer': typeof AppTrainerRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/app': typeof AppIndexRoute
  '/app/academy/batches': typeof AppAcademyBatchesRouteWithChildren
  '/app/academy/certificates': typeof AppAcademyCertificatesRoute
  '/app/academy/courses': typeof AppAcademyCoursesRoute
  '/app/academy/fees': typeof AppAcademyFeesRoute
  '/app/academy/students': typeof AppAcademyStudentsRoute
  '/app/academy/trainers': typeof AppAcademyTrainersRoute
  '/app/finance/categories': typeof AppFinanceCategoriesRoute
  '/app/finance/expenses': typeof AppFinanceExpensesRoute
  '/app/finance/payouts': typeof AppFinancePayoutsRoute
  '/app/finance/revenue': typeof AppFinanceRevenueRoute
  '/app/franchisees/$franchiseeId': typeof AppFranchiseesFranchiseeIdRoute
  '/app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/app/inventory/movements': typeof AppInventoryMovementsRoute
  '/app/inventory/products': typeof AppInventoryProductsRoute
  '/app/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/app/inventory/stock': typeof AppInventoryStockRoute
  '/app/inventory/suppliers': typeof AppInventorySuppliersRoute
  '/app/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/academy': typeof AppAcademyIndexRoute
  '/app/finance': typeof AppFinanceIndexRoute
  '/app/inventory': typeof AppInventoryIndexRoute
  '/app/academy/batches/$batchId': typeof AppAcademyBatchesBatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/academy': typeof AppAcademyRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRouteWithChildren
  '/app/franchisees': typeof AppFranchiseesRouteWithChildren
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/my-franchise': typeof AppMyFranchiseRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/trainer': typeof AppTrainerRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/app/': typeof AppIndexRoute
  '/app/academy/batches': typeof AppAcademyBatchesRouteWithChildren
  '/app/academy/certificates': typeof AppAcademyCertificatesRoute
  '/app/academy/courses': typeof AppAcademyCoursesRoute
  '/app/academy/fees': typeof AppAcademyFeesRoute
  '/app/academy/students': typeof AppAcademyStudentsRoute
  '/app/academy/trainers': typeof AppAcademyTrainersRoute
  '/app/finance/categories': typeof AppFinanceCategoriesRoute
  '/app/finance/expenses': typeof AppFinanceExpensesRoute
  '/app/finance/payouts': typeof AppFinancePayoutsRoute
  '/app/finance/revenue': typeof AppFinanceRevenueRoute
  '/app/franchisees/$franchiseeId': typeof AppFranchiseesFranchiseeIdRoute
  '/app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/app/inventory/movements': typeof AppInventoryMovementsRoute
  '/app/inventory/products': typeof AppInventoryProductsRoute
  '/app/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/app/inventory/stock': typeof AppInventoryStockRoute
  '/app/inventory/suppliers': typeof AppInventorySuppliersRoute
  '/app/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/academy/': typeof AppAcademyIndexRoute
  '/app/finance/': typeof AppFinanceIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/academy/batches/$batchId': typeof AppAcademyBatchesBatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/academy'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/franchisees'
    | '/app/inventory'
    | '/app/leads'
    | '/app/my-franchise'
    | '/app/settings'
    | '/app/support'
    | '/app/trainer'
    | '/verify/$code'
    | '/app/'
    | '/app/academy/batches'
    | '/app/academy/certificates'
    | '/app/academy/courses'
    | '/app/academy/fees'
    | '/app/academy/students'
    | '/app/academy/trainers'
    | '/app/finance/categories'
    | '/app/finance/expenses'
    | '/app/finance/payouts'
    | '/app/finance/revenue'
    | '/app/franchisees/$franchiseeId'
    | '/app/inventory/categories'
    | '/app/inventory/movements'
    | '/app/inventory/products'
    | '/app/inventory/purchase-orders'
    | '/app/inventory/stock'
    | '/app/inventory/suppliers'
    | '/app/inventory/warehouses'
    | '/app/leads/$leadId'
    | '/app/academy/'
    | '/app/finance/'
    | '/app/inventory/'
    | '/app/academy/batches/$batchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/dashboard'
    | '/app/franchisees'
    | '/app/leads'
    | '/app/my-franchise'
    | '/app/settings'
    | '/app/support'
    | '/app/trainer'
    | '/verify/$code'
    | '/app'
    | '/app/academy/batches'
    | '/app/academy/certificates'
    | '/app/academy/courses'
    | '/app/academy/fees'
    | '/app/academy/students'
    | '/app/academy/trainers'
    | '/app/finance/categories'
    | '/app/finance/expenses'
    | '/app/finance/payouts'
    | '/app/finance/revenue'
    | '/app/franchisees/$franchiseeId'
    | '/app/inventory/categories'
    | '/app/inventory/movements'
    | '/app/inventory/products'
    | '/app/inventory/purchase-orders'
    | '/app/inventory/stock'
    | '/app/inventory/suppliers'
    | '/app/inventory/warehouses'
    | '/app/leads/$leadId'
    | '/app/academy'
    | '/app/finance'
    | '/app/inventory'
    | '/app/academy/batches/$batchId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/academy'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/franchisees'
    | '/app/inventory'
    | '/app/leads'
    | '/app/my-franchise'
    | '/app/settings'
    | '/app/support'
    | '/app/trainer'
    | '/verify/$code'
    | '/app/'
    | '/app/academy/batches'
    | '/app/academy/certificates'
    | '/app/academy/courses'
    | '/app/academy/fees'
    | '/app/academy/students'
    | '/app/academy/trainers'
    | '/app/finance/categories'
    | '/app/finance/expenses'
    | '/app/finance/payouts'
    | '/app/finance/revenue'
    | '/app/franchisees/$franchiseeId'
    | '/app/inventory/categories'
    | '/app/inventory/movements'
    | '/app/inventory/products'
    | '/app/inventory/purchase-orders'
    | '/app/inventory/stock'
    | '/app/inventory/suppliers'
    | '/app/inventory/warehouses'
    | '/app/leads/$leadId'
    | '/app/academy/'
    | '/app/finance/'
    | '/app/inventory/'
    | '/app/academy/batches/$batchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/trainer': {
      id: '/app/trainer'
      path: '/trainer'
      fullPath: '/app/trainer'
      preLoaderRoute: typeof AppTrainerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-franchise': {
      id: '/app/my-franchise'
      path: '/my-franchise'
      fullPath: '/app/my-franchise'
      preLoaderRoute: typeof AppMyFranchiseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/franchisees': {
      id: '/app/franchisees'
      path: '/franchisees'
      fullPath: '/app/franchisees'
      preLoaderRoute: typeof AppFranchiseesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academy': {
      id: '/app/academy'
      path: '/academy'
      fullPath: '/app/academy'
      preLoaderRoute: typeof AppAcademyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory/': {
      id: '/app/inventory/'
      path: '/'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/finance/': {
      id: '/app/finance/'
      path: '/'
      fullPath: '/app/finance/'
      preLoaderRoute: typeof AppFinanceIndexRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/app/academy/': {
      id: '/app/academy/'
      path: '/'
      fullPath: '/app/academy/'
      preLoaderRoute: typeof AppAcademyIndexRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/app/leads/$leadId': {
      id: '/app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/app/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/app/inventory/warehouses': {
      id: '/app/inventory/warehouses'
      path: '/warehouses'
      fullPath: '/app/inventory/warehouses'
      preLoaderRoute: typeof AppInventoryWarehousesRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/suppliers': {
      id: '/app/inventory/suppliers'
      path: '/suppliers'
      fullPath: '/app/inventory/suppliers'
      preLoaderRoute: typeof AppInventorySuppliersRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/stock': {
      id: '/app/inventory/stock'
      path: '/stock'
      fullPath: '/app/inventory/stock'
      preLoaderRoute: typeof AppInventoryStockRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/purchase-orders': {
      id: '/app/inventory/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/inventory/purchase-orders'
      preLoaderRoute: typeof AppInventoryPurchaseOrdersRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/products': {
      id: '/app/inventory/products'
      path: '/products'
      fullPath: '/app/inventory/products'
      preLoaderRoute: typeof AppInventoryProductsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/movements': {
      id: '/app/inventory/movements'
      path: '/movements'
      fullPath: '/app/inventory/movements'
      preLoaderRoute: typeof AppInventoryMovementsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/categories': {
      id: '/app/inventory/categories'
      path: '/categories'
      fullPath: '/app/inventory/categories'
      preLoaderRoute: typeof AppInventoryCategoriesRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/franchisees/$franchiseeId': {
      id: '/app/franchisees/$franchiseeId'
      path: '/$franchiseeId'
      fullPath: '/app/franchisees/$franchiseeId'
      preLoaderRoute: typeof AppFranchiseesFranchiseeIdRouteImport
      parentRoute: typeof AppFranchiseesRoute
    }
    '/app/finance/revenue': {
      id: '/app/finance/revenue'
      path: '/revenue'
      fullPath: '/app/finance/revenue'
      preLoaderRoute: typeof AppFinanceRevenueRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/app/finance/payouts': {
      id: '/app/finance/payouts'
      path: '/payouts'
      fullPath: '/app/finance/payouts'
      preLoaderRoute: typeof AppFinancePayoutsRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/app/finance/expenses': {
      id: '/app/finance/expenses'
      path: '/expenses'
      fullPath: '/app/finance/expenses'
      preLoaderRoute: typeof AppFinanceExpensesRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/app/finance/categories': {
      id: '/app/finance/categories'
      path: '/categories'
      fullPath: '/app/finance/categories'
      preLoaderRoute: typeof AppFinanceCategoriesRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/app/academy/trainers': {
      id: '/app/academy/trainers'
      path: '/trainers'
      fullPath: '/app/academy/trainers'
      preLoaderRoute: typeof AppAcademyTrainersRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/app/academy/students': {
      id: '/app/academy/students'
      path: '/students'
      fullPath: '/app/academy/students'
      preLoaderRoute: typeof AppAcademyStudentsRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/app/academy/fees': {
      id: '/app/academy/fees'
      path: '/fees'
      fullPath: '/app/academy/fees'
      preLoaderRoute: typeof AppAcademyFeesRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/app/academy/courses': {
      id: '/app/academy/courses'
      path: '/courses'
      fullPath: '/app/academy/courses'
      preLoaderRoute: typeof AppAcademyCoursesRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/app/academy/certificates': {
      id: '/app/academy/certificates'
      path: '/certificates'
      fullPath: '/app/academy/certificates'
      preLoaderRoute: typeof AppAcademyCertificatesRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/app/academy/batches': {
      id: '/app/academy/batches'
      path: '/batches'
      fullPath: '/app/academy/batches'
      preLoaderRoute: typeof AppAcademyBatchesRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/app/academy/batches/$batchId': {
      id: '/app/academy/batches/$batchId'
      path: '/$batchId'
      fullPath: '/app/academy/batches/$batchId'
      preLoaderRoute: typeof AppAcademyBatchesBatchIdRouteImport
      parentRoute: typeof AppAcademyBatchesRoute
    }
  }
}

interface AppAcademyBatchesRouteChildren {
  AppAcademyBatchesBatchIdRoute: typeof AppAcademyBatchesBatchIdRoute
}

const AppAcademyBatchesRouteChildren: AppAcademyBatchesRouteChildren = {
  AppAcademyBatchesBatchIdRoute: AppAcademyBatchesBatchIdRoute,
}

const AppAcademyBatchesRouteWithChildren =
  AppAcademyBatchesRoute._addFileChildren(AppAcademyBatchesRouteChildren)

interface AppAcademyRouteChildren {
  AppAcademyBatchesRoute: typeof AppAcademyBatchesRouteWithChildren
  AppAcademyCertificatesRoute: typeof AppAcademyCertificatesRoute
  AppAcademyCoursesRoute: typeof AppAcademyCoursesRoute
  AppAcademyFeesRoute: typeof AppAcademyFeesRoute
  AppAcademyStudentsRoute: typeof AppAcademyStudentsRoute
  AppAcademyTrainersRoute: typeof AppAcademyTrainersRoute
  AppAcademyIndexRoute: typeof AppAcademyIndexRoute
}

const AppAcademyRouteChildren: AppAcademyRouteChildren = {
  AppAcademyBatchesRoute: AppAcademyBatchesRouteWithChildren,
  AppAcademyCertificatesRoute: AppAcademyCertificatesRoute,
  AppAcademyCoursesRoute: AppAcademyCoursesRoute,
  AppAcademyFeesRoute: AppAcademyFeesRoute,
  AppAcademyStudentsRoute: AppAcademyStudentsRoute,
  AppAcademyTrainersRoute: AppAcademyTrainersRoute,
  AppAcademyIndexRoute: AppAcademyIndexRoute,
}

const AppAcademyRouteWithChildren = AppAcademyRoute._addFileChildren(
  AppAcademyRouteChildren,
)

interface AppFinanceRouteChildren {
  AppFinanceCategoriesRoute: typeof AppFinanceCategoriesRoute
  AppFinanceExpensesRoute: typeof AppFinanceExpensesRoute
  AppFinancePayoutsRoute: typeof AppFinancePayoutsRoute
  AppFinanceRevenueRoute: typeof AppFinanceRevenueRoute
  AppFinanceIndexRoute: typeof AppFinanceIndexRoute
}

const AppFinanceRouteChildren: AppFinanceRouteChildren = {
  AppFinanceCategoriesRoute: AppFinanceCategoriesRoute,
  AppFinanceExpensesRoute: AppFinanceExpensesRoute,
  AppFinancePayoutsRoute: AppFinancePayoutsRoute,
  AppFinanceRevenueRoute: AppFinanceRevenueRoute,
  AppFinanceIndexRoute: AppFinanceIndexRoute,
}

const AppFinanceRouteWithChildren = AppFinanceRoute._addFileChildren(
  AppFinanceRouteChildren,
)

interface AppFranchiseesRouteChildren {
  AppFranchiseesFranchiseeIdRoute: typeof AppFranchiseesFranchiseeIdRoute
}

const AppFranchiseesRouteChildren: AppFranchiseesRouteChildren = {
  AppFranchiseesFranchiseeIdRoute: AppFranchiseesFranchiseeIdRoute,
}

const AppFranchiseesRouteWithChildren = AppFranchiseesRoute._addFileChildren(
  AppFranchiseesRouteChildren,
)

interface AppInventoryRouteChildren {
  AppInventoryCategoriesRoute: typeof AppInventoryCategoriesRoute
  AppInventoryMovementsRoute: typeof AppInventoryMovementsRoute
  AppInventoryProductsRoute: typeof AppInventoryProductsRoute
  AppInventoryPurchaseOrdersRoute: typeof AppInventoryPurchaseOrdersRoute
  AppInventoryStockRoute: typeof AppInventoryStockRoute
  AppInventorySuppliersRoute: typeof AppInventorySuppliersRoute
  AppInventoryWarehousesRoute: typeof AppInventoryWarehousesRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryCategoriesRoute: AppInventoryCategoriesRoute,
  AppInventoryMovementsRoute: AppInventoryMovementsRoute,
  AppInventoryProductsRoute: AppInventoryProductsRoute,
  AppInventoryPurchaseOrdersRoute: AppInventoryPurchaseOrdersRoute,
  AppInventoryStockRoute: AppInventoryStockRoute,
  AppInventorySuppliersRoute: AppInventorySuppliersRoute,
  AppInventoryWarehousesRoute: AppInventoryWarehousesRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppLeadsRouteChildren {
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppRouteChildren {
  AppAcademyRoute: typeof AppAcademyRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRouteWithChildren
  AppFranchiseesRoute: typeof AppFranchiseesRouteWithChildren
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppMyFranchiseRoute: typeof AppMyFranchiseRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTrainerRoute: typeof AppTrainerRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademyRoute: AppAcademyRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRouteWithChildren,
  AppFranchiseesRoute: AppFranchiseesRouteWithChildren,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppMyFranchiseRoute: AppMyFranchiseRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTrainerRoute: AppTrainerRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  VerifyCodeRoute: VerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
