/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as WebinarSlugRouteImport } from './routes/webinar.$slug'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as InvoiceTokenRouteImport } from './routes/invoice.$token'
import { Route as AppWebinarsRouteImport } from './routes/app.webinars'
import { Route as AppTrainerRouteImport } from './routes/app.trainer'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppMyFranchiseRouteImport } from './routes/app.my-franchise'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppHrRouteImport } from './routes/app.hr'
import { Route as AppFranchiseesRouteImport } from './routes/app.franchisees'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAcademyRouteImport } from './routes/app.academy'
import { Route as AppWebinarsIndexRouteImport } from './routes/app.webinars.index'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as AppPosIndexRouteImport } from './routes/app.pos.index'
import { Route as AppInventoryIndexRouteImport } from './routes/app.inventory.index'
import { Route as AppHrIndexRouteImport } from './routes/app.hr.index'
import { Route as AppFinanceIndexRouteImport } from './routes/app.finance.index'
import { Route as AppAcademyIndexRouteImport } from './routes/app.academy.index'
import { Route as AppWebinarsAnalyticsRouteImport } from './routes/app.webinars.analytics'
import { Route as AppWebinarsWebinarIdRouteImport } from './routes/app.webinars.$webinarId'
import { Route as AppSettingsTeamRouteImport } from './routes/app.settings.team'
import { Route as AppSettingsSocialRouteImport } from './routes/app.settings.social'
import { Route as AppSettingsLeadRoutingRouteImport } from './routes/app.settings.lead-routing'
import { Route as AppPosOrdersRouteImport } from './routes/app.pos.orders'
import { Route as AppPosAnalyticsRouteImport } from './routes/app.pos.analytics'
import { Route as AppLeadsLeadIdRouteImport } from './routes/app.leads.$leadId'
import { Route as AppInventoryWarehousesRouteImport } from './routes/app.inventory.warehouses'
import { Route as AppInventorySuppliersRouteImport } from './routes/app.inventory.suppliers'
import { Route as AppInventoryStockRouteImport } from './routes/app.inventory.stock'
import { Route as AppInventoryPurchaseOrdersRouteImport } from './routes/app.inventory.purchase-orders'
import { Route as AppInventoryProductsRouteImport } from './routes/app.inventory.products'
import { Route as AppInventoryMovementsRouteImport } from './routes/app.inventory.movements'
import { Route as AppInventoryCategoriesRouteImport } from './routes/app.inventory.categories'
import { Route as AppHrPayrollRouteImport } from './routes/app.hr.payroll'
import { Route as AppHrLeaveRouteImport } from './routes/app.hr.leave'
import { Route as AppHrEmployeesRouteImport } from './routes/app.hr.employees'
import { Route as AppHrAttendanceRouteImport } from './routes/app.hr.attendance'
import { Route as AppFranchiseesFranchiseeIdRouteImport } from './routes/app.franchisees.$franchiseeId'
import { Route as AppFinanceRevenueModelRouteImport } from './routes/app.finance.revenue-model'
import { Route as AppFinanceRevenueRouteImport } from './routes/app.finance.revenue'
import { Route as AppFinancePayoutsRouteImport } from './routes/app.finance.payouts'
import { Route as AppFinanceExpensesRouteImport } from './routes/app.finance.expenses'
import { Route as AppFinanceCategoriesRouteImport } from './routes/app.finance.categories'
import { Route as AppAcademyTrainersRouteImport } from './routes/app.academy.trainers'
import { Route as AppAcademyStudentsRouteImport } from './routes/app.academy.students'
import { Route as AppAcademyFeesRouteImport } from './routes/app.academy.fees'
import { Route as AppAcademyCoursesRouteImport } from './routes/app.academy.courses'
import { Route as AppAcademyCertificatesRouteImport } from './routes/app.academy.certificates'
import { Route as AppAcademyBatchesRouteImport } from './routes/app.academy.batches'
import { Route as ApiPublicWebinarRemindersRouteImport } from './routes/api/public/webinar-reminders'
import { Route as ApiPublicWebinarRegisterHookRouteImport } from './routes/api/public/webinar-register-hook'
import { Route as ApiPublicSocialLeadHookRouteImport } from './routes/api/public/social-lead-hook'
import { Route as AppPosOrdersOrderIdRouteImport } from './routes/app.pos.orders.$orderId'
import { Route as AppAcademyBatchesBatchIdRouteImport } from './routes/app.academy.batches.$batchId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const WebinarSlugRoute = WebinarSlugRouteImport.update({
  id: '/webinar/$slug',
  path: '/webinar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceTokenRoute = InvoiceTokenRouteImport.update({
  id: '/invoice/$token',
  path: '/invoice/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebinarsRoute = AppWebinarsRouteImport.update({
  id: '/webinars',
  path: '/webinars',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainerRoute = AppTrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppMyFranchiseRoute = AppMyFranchiseRouteImport.update({
  id: '/my-franchise',
  path: '/my-franchise',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppFranchiseesRoute = AppFranchiseesRouteImport.update({
  id: '/franchisees',
  path: '/franchisees',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademyRoute = AppAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AppRoute,
} as any)
const AppWebinarsIndexRoute = AppWebinarsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWebinarsRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppPosIndexRoute = AppPosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPosRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppHrIndexRoute = AppHrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHrRoute,
} as any)
const AppFinanceIndexRoute = AppFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppAcademyIndexRoute = AppAcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAcademyRoute,
} as any)
const AppWebinarsAnalyticsRoute = AppWebinarsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppWebinarsRoute,
} as any)
const AppWebinarsWebinarIdRoute = AppWebinarsWebinarIdRouteImport.update({
  id: '/$webinarId',
  path: '/$webinarId',
  getParentRoute: () => AppWebinarsRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSocialRoute = AppSettingsSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsLeadRoutingRoute = AppSettingsLeadRoutingRouteImport.update({
  id: '/lead-routing',
  path: '/lead-routing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppPosOrdersRoute = AppPosOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppPosRoute,
} as any)
const AppPosAnalyticsRoute = AppPosAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppPosRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppInventoryWarehousesRoute = AppInventoryWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventorySuppliersRoute = AppInventorySuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryStockRoute = AppInventoryStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryPurchaseOrdersRoute =
  AppInventoryPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryProductsRoute = AppInventoryProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryMovementsRoute = AppInventoryMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryCategoriesRoute = AppInventoryCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppHrPayrollRoute = AppHrPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrLeaveRoute = AppHrLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrEmployeesRoute = AppHrEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrAttendanceRoute = AppHrAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppHrRoute,
} as any)
const AppFranchiseesFranchiseeIdRoute =
  AppFranchiseesFranchiseeIdRouteImport.update({
    id: '/$franchiseeId',
    path: '/$franchiseeId',
    getParentRoute: () => AppFranchiseesRoute,
  } as any)
const AppFinanceRevenueModelRoute = AppFinanceRevenueModelRouteImport.update({
  id: '/revenue-model',
  path: '/revenue-model',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinanceRevenueRoute = AppFinanceRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinancePayoutsRoute = AppFinancePayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinanceExpensesRoute = AppFinanceExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppFinanceCategoriesRoute = AppFinanceCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppFinanceRoute,
} as any)
const AppAcademyTrainersRoute = AppAcademyTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AppAcademyRoute,
} as any)
const AppAcademyStudentsRoute = AppAcademyStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppAcademyRoute,
} as any)
const AppAcademyFeesRoute = AppAcademyFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppAcademyRoute,
} as any)
const AppAcademyCoursesRoute = AppAcademyCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppAcademyRoute,
} as any)
const AppAcademyCertificatesRoute = AppAcademyCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppAcademyRoute,
} as any)
const AppAcademyBatchesRoute = AppAcademyBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AppAcademyRoute,
} as any)
const ApiPublicWebinarRemindersRoute =
  ApiPublicWebinarRemindersRouteImport.update({
    id: '/api/public/webinar-reminders',
    path: '/api/public/webinar-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebinarRegisterHookRoute =
  ApiPublicWebinarRegisterHookRouteImport.update({
    id: '/api/public/webinar-register-hook',
    path: '/api/public/webinar-register-hook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSocialLeadHookRoute = ApiPublicSocialLeadHookRouteImport.update({
  id: '/api/public/social-lead-hook',
  path: '/api/public/social-lead-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPosOrdersOrderIdRoute = AppPosOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AppPosOrdersRoute,
} as any)
const AppAcademyBatchesBatchIdRoute =
  AppAcademyBatchesBatchIdRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => AppAcademyBatchesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/academy': typeof AppAcademyRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRouteWithChildren
  '/app/franchisees': typeof AppFranchiseesRouteWithChildren
  '/app/hr': typeof AppHrRouteWithChildren
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/my-franchise': typeof AppMyFranchiseRoute
  '/app/pos': typeof AppPosRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/support': typeof AppSupportRoute
  '/app/trainer': typeof AppTrainerRoute
  '/app/webinars': typeof AppWebinarsRouteWithChildren
  '/invoice/$token': typeof InvoiceTokenRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/webinar/$slug': typeof WebinarSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/social-lead-hook': typeof ApiPublicSocialLeadHookRoute
  '/api/public/webinar-register-hook': typeof ApiPublicWebinarRegisterHookRoute
  '/api/public/webinar-reminders': typeof ApiPublicWebinarRemindersRoute
  '/app/academy/batches': typeof AppAcademyBatchesRouteWithChildren
  '/app/academy/certificates': typeof AppAcademyCertificatesRoute
  '/app/academy/courses': typeof AppAcademyCoursesRoute
  '/app/academy/fees': typeof AppAcademyFeesRoute
  '/app/academy/students': typeof AppAcademyStudentsRoute
  '/app/academy/trainers': typeof AppAcademyTrainersRoute
  '/app/finance/categories': typeof AppFinanceCategoriesRoute
  '/app/finance/expenses': typeof AppFinanceExpensesRoute
  '/app/finance/payouts': typeof AppFinancePayoutsRoute
  '/app/finance/revenue': typeof AppFinanceRevenueRoute
  '/app/finance/revenue-model': typeof AppFinanceRevenueModelRoute
  '/app/franchisees/$franchiseeId': typeof AppFranchiseesFranchiseeIdRoute
  '/app/hr/attendance': typeof AppHrAttendanceRoute
  '/app/hr/employees': typeof AppHrEmployeesRoute
  '/app/hr/leave': typeof AppHrLeaveRoute
  '/app/hr/payroll': typeof AppHrPayrollRoute
  '/app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/app/inventory/movements': typeof AppInventoryMovementsRoute
  '/app/inventory/products': typeof AppInventoryProductsRoute
  '/app/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/app/inventory/stock': typeof AppInventoryStockRoute
  '/app/inventory/suppliers': typeof AppInventorySuppliersRoute
  '/app/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/pos/analytics': typeof AppPosAnalyticsRoute
  '/app/pos/orders': typeof AppPosOrdersRouteWithChildren
  '/app/settings/lead-routing': typeof AppSettingsLeadRoutingRoute
  '/app/settings/social': typeof AppSettingsSocialRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/webinars/$webinarId': typeof AppWebinarsWebinarIdRoute
  '/app/webinars/analytics': typeof AppWebinarsAnalyticsRoute
  '/app/academy/': typeof AppAcademyIndexRoute
  '/app/finance/': typeof AppFinanceIndexRoute
  '/app/hr/': typeof AppHrIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/pos/': typeof AppPosIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/webinars/': typeof AppWebinarsIndexRoute
  '/app/academy/batches/$batchId': typeof AppAcademyBatchesBatchIdRoute
  '/app/pos/orders/$orderId': typeof AppPosOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/franchisees': typeof AppFranchiseesRouteWithChildren
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/my-franchise': typeof AppMyFranchiseRoute
  '/app/support': typeof AppSupportRoute
  '/app/trainer': typeof AppTrainerRoute
  '/invoice/$token': typeof InvoiceTokenRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/webinar/$slug': typeof WebinarSlugRoute
  '/app': typeof AppIndexRoute
  '/api/public/social-lead-hook': typeof ApiPublicSocialLeadHookRoute
  '/api/public/webinar-register-hook': typeof ApiPublicWebinarRegisterHookRoute
  '/api/public/webinar-reminders': typeof ApiPublicWebinarRemindersRoute
  '/app/academy/batches': typeof AppAcademyBatchesRouteWithChildren
  '/app/academy/certificates': typeof AppAcademyCertificatesRoute
  '/app/academy/courses': typeof AppAcademyCoursesRoute
  '/app/academy/fees': typeof AppAcademyFeesRoute
  '/app/academy/students': typeof AppAcademyStudentsRoute
  '/app/academy/trainers': typeof AppAcademyTrainersRoute
  '/app/finance/categories': typeof AppFinanceCategoriesRoute
  '/app/finance/expenses': typeof AppFinanceExpensesRoute
  '/app/finance/payouts': typeof AppFinancePayoutsRoute
  '/app/finance/revenue': typeof AppFinanceRevenueRoute
  '/app/finance/revenue-model': typeof AppFinanceRevenueModelRoute
  '/app/franchisees/$franchiseeId': typeof AppFranchiseesFranchiseeIdRoute
  '/app/hr/attendance': typeof AppHrAttendanceRoute
  '/app/hr/employees': typeof AppHrEmployeesRoute
  '/app/hr/leave': typeof AppHrLeaveRoute
  '/app/hr/payroll': typeof AppHrPayrollRoute
  '/app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/app/inventory/movements': typeof AppInventoryMovementsRoute
  '/app/inventory/products': typeof AppInventoryProductsRoute
  '/app/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/app/inventory/stock': typeof AppInventoryStockRoute
  '/app/inventory/suppliers': typeof AppInventorySuppliersRoute
  '/app/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/pos/analytics': typeof AppPosAnalyticsRoute
  '/app/pos/orders': typeof AppPosOrdersRouteWithChildren
  '/app/settings/lead-routing': typeof AppSettingsLeadRoutingRoute
  '/app/settings/social': typeof AppSettingsSocialRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/webinars/$webinarId': typeof AppWebinarsWebinarIdRoute
  '/app/webinars/analytics': typeof AppWebinarsAnalyticsRoute
  '/app/academy': typeof AppAcademyIndexRoute
  '/app/finance': typeof AppFinanceIndexRoute
  '/app/hr': typeof AppHrIndexRoute
  '/app/inventory': typeof AppInventoryIndexRoute
  '/app/pos': typeof AppPosIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/webinars': typeof AppWebinarsIndexRoute
  '/app/academy/batches/$batchId': typeof AppAcademyBatchesBatchIdRoute
  '/app/pos/orders/$orderId': typeof AppPosOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/academy': typeof AppAcademyRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRouteWithChildren
  '/app/franchisees': typeof AppFranchiseesRouteWithChildren
  '/app/hr': typeof AppHrRouteWithChildren
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/my-franchise': typeof AppMyFranchiseRoute
  '/app/pos': typeof AppPosRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/support': typeof AppSupportRoute
  '/app/trainer': typeof AppTrainerRoute
  '/app/webinars': typeof AppWebinarsRouteWithChildren
  '/invoice/$token': typeof InvoiceTokenRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/webinar/$slug': typeof WebinarSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/social-lead-hook': typeof ApiPublicSocialLeadHookRoute
  '/api/public/webinar-register-hook': typeof ApiPublicWebinarRegisterHookRoute
  '/api/public/webinar-reminders': typeof ApiPublicWebinarRemindersRoute
  '/app/academy/batches': typeof AppAcademyBatchesRouteWithChildren
  '/app/academy/certificates': typeof AppAcademyCertificatesRoute
  '/app/academy/courses': typeof AppAcademyCoursesRoute
  '/app/academy/fees': typeof AppAcademyFeesRoute
  '/app/academy/students': typeof AppAcademyStudentsRoute
  '/app/academy/trainers': typeof AppAcademyTrainersRoute
  '/app/finance/categories': typeof AppFinanceCategoriesRoute
  '/app/finance/expenses': typeof AppFinanceExpensesRoute
  '/app/finance/payouts': typeof AppFinancePayoutsRoute
  '/app/finance/revenue': typeof AppFinanceRevenueRoute
  '/app/finance/revenue-model': typeof AppFinanceRevenueModelRoute
  '/app/franchisees/$franchiseeId': typeof AppFranchiseesFranchiseeIdRoute
  '/app/hr/attendance': typeof AppHrAttendanceRoute
  '/app/hr/employees': typeof AppHrEmployeesRoute
  '/app/hr/leave': typeof AppHrLeaveRoute
  '/app/hr/payroll': typeof AppHrPayrollRoute
  '/app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/app/inventory/movements': typeof AppInventoryMovementsRoute
  '/app/inventory/products': typeof AppInventoryProductsRoute
  '/app/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/app/inventory/stock': typeof AppInventoryStockRoute
  '/app/inventory/suppliers': typeof AppInventorySuppliersRoute
  '/app/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/pos/analytics': typeof AppPosAnalyticsRoute
  '/app/pos/orders': typeof AppPosOrdersRouteWithChildren
  '/app/settings/lead-routing': typeof AppSettingsLeadRoutingRoute
  '/app/settings/social': typeof AppSettingsSocialRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/webinars/$webinarId': typeof AppWebinarsWebinarIdRoute
  '/app/webinars/analytics': typeof AppWebinarsAnalyticsRoute
  '/app/academy/': typeof AppAcademyIndexRoute
  '/app/finance/': typeof AppFinanceIndexRoute
  '/app/hr/': typeof AppHrIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/pos/': typeof AppPosIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/webinars/': typeof AppWebinarsIndexRoute
  '/app/academy/batches/$batchId': typeof AppAcademyBatchesBatchIdRoute
  '/app/pos/orders/$orderId': typeof AppPosOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/academy'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/franchisees'
    | '/app/hr'
    | '/app/inventory'
    | '/app/leads'
    | '/app/my-franchise'
    | '/app/pos'
    | '/app/settings'
    | '/app/support'
    | '/app/trainer'
    | '/app/webinars'
    | '/invoice/$token'
    | '/verify/$code'
    | '/webinar/$slug'
    | '/app/'
    | '/api/public/social-lead-hook'
    | '/api/public/webinar-register-hook'
    | '/api/public/webinar-reminders'
    | '/app/academy/batches'
    | '/app/academy/certificates'
    | '/app/academy/courses'
    | '/app/academy/fees'
    | '/app/academy/students'
    | '/app/academy/trainers'
    | '/app/finance/categories'
    | '/app/finance/expenses'
    | '/app/finance/payouts'
    | '/app/finance/revenue'
    | '/app/finance/revenue-model'
    | '/app/franchisees/$franchiseeId'
    | '/app/hr/attendance'
    | '/app/hr/employees'
    | '/app/hr/leave'
    | '/app/hr/payroll'
    | '/app/inventory/categories'
    | '/app/inventory/movements'
    | '/app/inventory/products'
    | '/app/inventory/purchase-orders'
    | '/app/inventory/stock'
    | '/app/inventory/suppliers'
    | '/app/inventory/warehouses'
    | '/app/leads/$leadId'
    | '/app/pos/analytics'
    | '/app/pos/orders'
    | '/app/settings/lead-routing'
    | '/app/settings/social'
    | '/app/settings/team'
    | '/app/webinars/$webinarId'
    | '/app/webinars/analytics'
    | '/app/academy/'
    | '/app/finance/'
    | '/app/hr/'
    | '/app/inventory/'
    | '/app/pos/'
    | '/app/settings/'
    | '/app/webinars/'
    | '/app/academy/batches/$batchId'
    | '/app/pos/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/dashboard'
    | '/app/franchisees'
    | '/app/leads'
    | '/app/my-franchise'
    | '/app/support'
    | '/app/trainer'
    | '/invoice/$token'
    | '/verify/$code'
    | '/webinar/$slug'
    | '/app'
    | '/api/public/social-lead-hook'
    | '/api/public/webinar-register-hook'
    | '/api/public/webinar-reminders'
    | '/app/academy/batches'
    | '/app/academy/certificates'
    | '/app/academy/courses'
    | '/app/academy/fees'
    | '/app/academy/students'
    | '/app/academy/trainers'
    | '/app/finance/categories'
    | '/app/finance/expenses'
    | '/app/finance/payouts'
    | '/app/finance/revenue'
    | '/app/finance/revenue-model'
    | '/app/franchisees/$franchiseeId'
    | '/app/hr/attendance'
    | '/app/hr/employees'
    | '/app/hr/leave'
    | '/app/hr/payroll'
    | '/app/inventory/categories'
    | '/app/inventory/movements'
    | '/app/inventory/products'
    | '/app/inventory/purchase-orders'
    | '/app/inventory/stock'
    | '/app/inventory/suppliers'
    | '/app/inventory/warehouses'
    | '/app/leads/$leadId'
    | '/app/pos/analytics'
    | '/app/pos/orders'
    | '/app/settings/lead-routing'
    | '/app/settings/social'
    | '/app/settings/team'
    | '/app/webinars/$webinarId'
    | '/app/webinars/analytics'
    | '/app/academy'
    | '/app/finance'
    | '/app/hr'
    | '/app/inventory'
    | '/app/pos'
    | '/app/settings'
    | '/app/webinars'
    | '/app/academy/batches/$batchId'
    | '/app/pos/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/academy'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/franchisees'
    | '/app/hr'
    | '/app/inventory'
    | '/app/leads'
    | '/app/my-franchise'
    | '/app/pos'
    | '/app/settings'
    | '/app/support'
    | '/app/trainer'
    | '/app/webinars'
    | '/invoice/$token'
    | '/verify/$code'
    | '/webinar/$slug'
    | '/app/'
    | '/api/public/social-lead-hook'
    | '/api/public/webinar-register-hook'
    | '/api/public/webinar-reminders'
    | '/app/academy/batches'
    | '/app/academy/certificates'
    | '/app/academy/courses'
    | '/app/academy/fees'
    | '/app/academy/students'
    | '/app/academy/trainers'
    | '/app/finance/categories'
    | '/app/finance/expenses'
    | '/app/finance/payouts'
    | '/app/finance/revenue'
    | '/app/finance/revenue-model'
    | '/app/franchisees/$franchiseeId'
    | '/app/hr/attendance'
    | '/app/hr/employees'
    | '/app/hr/leave'
    | '/app/hr/payroll'
    | '/app/inventory/categories'
    | '/app/inventory/movements'
    | '/app/inventory/products'
    | '/app/inventory/purchase-orders'
    | '/app/inventory/stock'
    | '/app/inventory/suppliers'
    | '/app/inventory/warehouses'
    | '/app/leads/$leadId'
    | '/app/pos/analytics'
    | '/app/pos/orders'
    | '/app/settings/lead-routing'
    | '/app/settings/social'
    | '/app/settings/team'
    | '/app/webinars/$webinarId'
    | '/app/webinars/analytics'
    | '/app/academy/'
    | '/app/finance/'
    | '/app/hr/'
    | '/app/inventory/'
    | '/app/pos/'
    | '/app/settings/'
    | '/app/webinars/'
    | '/app/academy/batches/$batchId'
    | '/app/pos/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  InvoiceTokenRoute: typeof InvoiceTokenRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  WebinarSlugRoute: typeof WebinarSlugRoute
  ApiPublicSocialLeadHookRoute: typeof ApiPublicSocialLeadHookRoute
  ApiPublicWebinarRegisterHookRoute: typeof ApiPublicWebinarRegisterHookRoute
  ApiPublicWebinarRemindersRoute: typeof ApiPublicWebinarRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/webinar/$slug': {
      id: '/webinar/$slug'
      path: '/webinar/$slug'
      fullPath: '/webinar/$slug'
      preLoaderRoute: typeof WebinarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$token': {
      id: '/invoice/$token'
      path: '/invoice/$token'
      fullPath: '/invoice/$token'
      preLoaderRoute: typeof InvoiceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/webinars': {
      id: '/app/webinars'
      path: '/webinars'
      fullPath: '/app/webinars'
      preLoaderRoute: typeof AppWebinarsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trainer': {
      id: '/app/trainer'
      path: '/trainer'
      fullPath: '/app/trainer'
      preLoaderRoute: typeof AppTrainerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-franchise': {
      id: '/app/my-franchise'
      path: '/my-franchise'
      fullPath: '/app/my-franchise'
      preLoaderRoute: typeof AppMyFranchiseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr': {
      id: '/app/hr'
      path: '/hr'
      fullPath: '/app/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/franchisees': {
      id: '/app/franchisees'
      path: '/franchisees'
      fullPath: '/app/franchisees'
      preLoaderRoute: typeof AppFranchiseesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academy': {
      id: '/app/academy'
      path: '/academy'
      fullPath: '/app/academy'
      preLoaderRoute: typeof AppAcademyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webinars/': {
      id: '/app/webinars/'
      path: '/'
      fullPath: '/app/webinars/'
      preLoaderRoute: typeof AppWebinarsIndexRouteImport
      parentRoute: typeof AppWebinarsRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/pos/': {
      id: '/app/pos/'
      path: '/'
      fullPath: '/app/pos/'
      preLoaderRoute: typeof AppPosIndexRouteImport
      parentRoute: typeof AppPosRoute
    }
    '/app/inventory/': {
      id: '/app/inventory/'
      path: '/'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/hr/': {
      id: '/app/hr/'
      path: '/'
      fullPath: '/app/hr/'
      preLoaderRoute: typeof AppHrIndexRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/app/finance/': {
      id: '/app/finance/'
      path: '/'
      fullPath: '/app/finance/'
      preLoaderRoute: typeof AppFinanceIndexRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/app/academy/': {
      id: '/app/academy/'
      path: '/'
      fullPath: '/app/academy/'
      preLoaderRoute: typeof AppAcademyIndexRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/app/webinars/analytics': {
      id: '/app/webinars/analytics'
      path: '/analytics'
      fullPath: '/app/webinars/analytics'
      preLoaderRoute: typeof AppWebinarsAnalyticsRouteImport
      parentRoute: typeof AppWebinarsRoute
    }
    '/app/webinars/$webinarId': {
      id: '/app/webinars/$webinarId'
      path: '/$webinarId'
      fullPath: '/app/webinars/$webinarId'
      preLoaderRoute: typeof AppWebinarsWebinarIdRouteImport
      parentRoute: typeof AppWebinarsRoute
    }
    '/app/settings/team': {
      id: '/app/settings/team'
      path: '/team'
      fullPath: '/app/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/social': {
      id: '/app/settings/social'
      path: '/social'
      fullPath: '/app/settings/social'
      preLoaderRoute: typeof AppSettingsSocialRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/lead-routing': {
      id: '/app/settings/lead-routing'
      path: '/lead-routing'
      fullPath: '/app/settings/lead-routing'
      preLoaderRoute: typeof AppSettingsLeadRoutingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/pos/orders': {
      id: '/app/pos/orders'
      path: '/orders'
      fullPath: '/app/pos/orders'
      preLoaderRoute: typeof AppPosOrdersRouteImport
      parentRoute: typeof AppPosRoute
    }
    '/app/pos/analytics': {
      id: '/app/pos/analytics'
      path: '/analytics'
      fullPath: '/app/pos/analytics'
      preLoaderRoute: typeof AppPosAnalyticsRouteImport
      parentRoute: typeof AppPosRoute
    }
    '/app/leads/$leadId': {
      id: '/app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/app/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/app/inventory/warehouses': {
      id: '/app/inventory/warehouses'
      path: '/warehouses'
      fullPath: '/app/inventory/warehouses'
      preLoaderRoute: typeof AppInventoryWarehousesRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/suppliers': {
      id: '/app/inventory/suppliers'
      path: '/suppliers'
      fullPath: '/app/inventory/suppliers'
      preLoaderRoute: typeof AppInventorySuppliersRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/stock': {
      id: '/app/inventory/stock'
      path: '/stock'
      fullPath: '/app/inventory/stock'
      preLoaderRoute: typeof AppInventoryStockRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/purchase-orders': {
      id: '/app/inventory/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/inventory/purchase-orders'
      preLoaderRoute: typeof AppInventoryPurchaseOrdersRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/products': {
      id: '/app/inventory/products'
      path: '/products'
      fullPath: '/app/inventory/products'
      preLoaderRoute: typeof AppInventoryProductsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/movements': {
      id: '/app/inventory/movements'
      path: '/movements'
      fullPath: '/app/inventory/movements'
      preLoaderRoute: typeof AppInventoryMovementsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/categories': {
      id: '/app/inventory/categories'
      path: '/categories'
      fullPath: '/app/inventory/categories'
      preLoaderRoute: typeof AppInventoryCategoriesRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/hr/payroll': {
      id: '/app/hr/payroll'
      path: '/payroll'
      fullPath: '/app/hr/payroll'
      preLoaderRoute: typeof AppHrPayrollRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/app/hr/leave': {
      id: '/app/hr/leave'
      path: '/leave'
      fullPath: '/app/hr/leave'
      preLoaderRoute: typeof AppHrLeaveRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/app/hr/employees': {
      id: '/app/hr/employees'
      path: '/employees'
      fullPath: '/app/hr/employees'
      preLoaderRoute: typeof AppHrEmployeesRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/app/hr/attendance': {
      id: '/app/hr/attendance'
      path: '/attendance'
      fullPath: '/app/hr/attendance'
      preLoaderRoute: typeof AppHrAttendanceRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/app/franchisees/$franchiseeId': {
      id: '/app/franchisees/$franchiseeId'
      path: '/$franchiseeId'
      fullPath: '/app/franchisees/$franchiseeId'
      preLoaderRoute: typeof AppFranchiseesFranchiseeIdRouteImport
      parentRoute: typeof AppFranchiseesRoute
    }
    '/app/finance/revenue-model': {
      id: '/app/finance/revenue-model'
      path: '/revenue-model'
      fullPath: '/app/finance/revenue-model'
      preLoaderRoute: typeof AppFinanceRevenueModelRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/app/finance/revenue': {
      id: '/app/finance/revenue'
      path: '/revenue'
      fullPath: '/app/finance/revenue'
      preLoaderRoute: typeof AppFinanceRevenueRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/app/finance/payouts': {
      id: '/app/finance/payouts'
      path: '/payouts'
      fullPath: '/app/finance/payouts'
      preLoaderRoute: typeof AppFinancePayoutsRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/app/finance/expenses': {
      id: '/app/finance/expenses'
      path: '/expenses'
      fullPath: '/app/finance/expenses'
      preLoaderRoute: typeof AppFinanceExpensesRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/app/finance/categories': {
      id: '/app/finance/categories'
      path: '/categories'
      fullPath: '/app/finance/categories'
      preLoaderRoute: typeof AppFinanceCategoriesRouteImport
      parentRoute: typeof AppFinanceRoute
    }
    '/app/academy/trainers': {
      id: '/app/academy/trainers'
      path: '/trainers'
      fullPath: '/app/academy/trainers'
      preLoaderRoute: typeof AppAcademyTrainersRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/app/academy/students': {
      id: '/app/academy/students'
      path: '/students'
      fullPath: '/app/academy/students'
      preLoaderRoute: typeof AppAcademyStudentsRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/app/academy/fees': {
      id: '/app/academy/fees'
      path: '/fees'
      fullPath: '/app/academy/fees'
      preLoaderRoute: typeof AppAcademyFeesRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/app/academy/courses': {
      id: '/app/academy/courses'
      path: '/courses'
      fullPath: '/app/academy/courses'
      preLoaderRoute: typeof AppAcademyCoursesRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/app/academy/certificates': {
      id: '/app/academy/certificates'
      path: '/certificates'
      fullPath: '/app/academy/certificates'
      preLoaderRoute: typeof AppAcademyCertificatesRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/app/academy/batches': {
      id: '/app/academy/batches'
      path: '/batches'
      fullPath: '/app/academy/batches'
      preLoaderRoute: typeof AppAcademyBatchesRouteImport
      parentRoute: typeof AppAcademyRoute
    }
    '/api/public/webinar-reminders': {
      id: '/api/public/webinar-reminders'
      path: '/api/public/webinar-reminders'
      fullPath: '/api/public/webinar-reminders'
      preLoaderRoute: typeof ApiPublicWebinarRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webinar-register-hook': {
      id: '/api/public/webinar-register-hook'
      path: '/api/public/webinar-register-hook'
      fullPath: '/api/public/webinar-register-hook'
      preLoaderRoute: typeof ApiPublicWebinarRegisterHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/social-lead-hook': {
      id: '/api/public/social-lead-hook'
      path: '/api/public/social-lead-hook'
      fullPath: '/api/public/social-lead-hook'
      preLoaderRoute: typeof ApiPublicSocialLeadHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pos/orders/$orderId': {
      id: '/app/pos/orders/$orderId'
      path: '/$orderId'
      fullPath: '/app/pos/orders/$orderId'
      preLoaderRoute: typeof AppPosOrdersOrderIdRouteImport
      parentRoute: typeof AppPosOrdersRoute
    }
    '/app/academy/batches/$batchId': {
      id: '/app/academy/batches/$batchId'
      path: '/$batchId'
      fullPath: '/app/academy/batches/$batchId'
      preLoaderRoute: typeof AppAcademyBatchesBatchIdRouteImport
      parentRoute: typeof AppAcademyBatchesRoute
    }
  }
}

interface AppAcademyBatchesRouteChildren {
  AppAcademyBatchesBatchIdRoute: typeof AppAcademyBatchesBatchIdRoute
}

const AppAcademyBatchesRouteChildren: AppAcademyBatchesRouteChildren = {
  AppAcademyBatchesBatchIdRoute: AppAcademyBatchesBatchIdRoute,
}

const AppAcademyBatchesRouteWithChildren =
  AppAcademyBatchesRoute._addFileChildren(AppAcademyBatchesRouteChildren)

interface AppAcademyRouteChildren {
  AppAcademyBatchesRoute: typeof AppAcademyBatchesRouteWithChildren
  AppAcademyCertificatesRoute: typeof AppAcademyCertificatesRoute
  AppAcademyCoursesRoute: typeof AppAcademyCoursesRoute
  AppAcademyFeesRoute: typeof AppAcademyFeesRoute
  AppAcademyStudentsRoute: typeof AppAcademyStudentsRoute
  AppAcademyTrainersRoute: typeof AppAcademyTrainersRoute
  AppAcademyIndexRoute: typeof AppAcademyIndexRoute
}

const AppAcademyRouteChildren: AppAcademyRouteChildren = {
  AppAcademyBatchesRoute: AppAcademyBatchesRouteWithChildren,
  AppAcademyCertificatesRoute: AppAcademyCertificatesRoute,
  AppAcademyCoursesRoute: AppAcademyCoursesRoute,
  AppAcademyFeesRoute: AppAcademyFeesRoute,
  AppAcademyStudentsRoute: AppAcademyStudentsRoute,
  AppAcademyTrainersRoute: AppAcademyTrainersRoute,
  AppAcademyIndexRoute: AppAcademyIndexRoute,
}

const AppAcademyRouteWithChildren = AppAcademyRoute._addFileChildren(
  AppAcademyRouteChildren,
)

interface AppFinanceRouteChildren {
  AppFinanceCategoriesRoute: typeof AppFinanceCategoriesRoute
  AppFinanceExpensesRoute: typeof AppFinanceExpensesRoute
  AppFinancePayoutsRoute: typeof AppFinancePayoutsRoute
  AppFinanceRevenueRoute: typeof AppFinanceRevenueRoute
  AppFinanceRevenueModelRoute: typeof AppFinanceRevenueModelRoute
  AppFinanceIndexRoute: typeof AppFinanceIndexRoute
}

const AppFinanceRouteChildren: AppFinanceRouteChildren = {
  AppFinanceCategoriesRoute: AppFinanceCategoriesRoute,
  AppFinanceExpensesRoute: AppFinanceExpensesRoute,
  AppFinancePayoutsRoute: AppFinancePayoutsRoute,
  AppFinanceRevenueRoute: AppFinanceRevenueRoute,
  AppFinanceRevenueModelRoute: AppFinanceRevenueModelRoute,
  AppFinanceIndexRoute: AppFinanceIndexRoute,
}

const AppFinanceRouteWithChildren = AppFinanceRoute._addFileChildren(
  AppFinanceRouteChildren,
)

interface AppFranchiseesRouteChildren {
  AppFranchiseesFranchiseeIdRoute: typeof AppFranchiseesFranchiseeIdRoute
}

const AppFranchiseesRouteChildren: AppFranchiseesRouteChildren = {
  AppFranchiseesFranchiseeIdRoute: AppFranchiseesFranchiseeIdRoute,
}

const AppFranchiseesRouteWithChildren = AppFranchiseesRoute._addFileChildren(
  AppFranchiseesRouteChildren,
)

interface AppHrRouteChildren {
  AppHrAttendanceRoute: typeof AppHrAttendanceRoute
  AppHrEmployeesRoute: typeof AppHrEmployeesRoute
  AppHrLeaveRoute: typeof AppHrLeaveRoute
  AppHrPayrollRoute: typeof AppHrPayrollRoute
  AppHrIndexRoute: typeof AppHrIndexRoute
}

const AppHrRouteChildren: AppHrRouteChildren = {
  AppHrAttendanceRoute: AppHrAttendanceRoute,
  AppHrEmployeesRoute: AppHrEmployeesRoute,
  AppHrLeaveRoute: AppHrLeaveRoute,
  AppHrPayrollRoute: AppHrPayrollRoute,
  AppHrIndexRoute: AppHrIndexRoute,
}

const AppHrRouteWithChildren = AppHrRoute._addFileChildren(AppHrRouteChildren)

interface AppInventoryRouteChildren {
  AppInventoryCategoriesRoute: typeof AppInventoryCategoriesRoute
  AppInventoryMovementsRoute: typeof AppInventoryMovementsRoute
  AppInventoryProductsRoute: typeof AppInventoryProductsRoute
  AppInventoryPurchaseOrdersRoute: typeof AppInventoryPurchaseOrdersRoute
  AppInventoryStockRoute: typeof AppInventoryStockRoute
  AppInventorySuppliersRoute: typeof AppInventorySuppliersRoute
  AppInventoryWarehousesRoute: typeof AppInventoryWarehousesRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryCategoriesRoute: AppInventoryCategoriesRoute,
  AppInventoryMovementsRoute: AppInventoryMovementsRoute,
  AppInventoryProductsRoute: AppInventoryProductsRoute,
  AppInventoryPurchaseOrdersRoute: AppInventoryPurchaseOrdersRoute,
  AppInventoryStockRoute: AppInventoryStockRoute,
  AppInventorySuppliersRoute: AppInventorySuppliersRoute,
  AppInventoryWarehousesRoute: AppInventoryWarehousesRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppLeadsRouteChildren {
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppPosOrdersRouteChildren {
  AppPosOrdersOrderIdRoute: typeof AppPosOrdersOrderIdRoute
}

const AppPosOrdersRouteChildren: AppPosOrdersRouteChildren = {
  AppPosOrdersOrderIdRoute: AppPosOrdersOrderIdRoute,
}

const AppPosOrdersRouteWithChildren = AppPosOrdersRoute._addFileChildren(
  AppPosOrdersRouteChildren,
)

interface AppPosRouteChildren {
  AppPosAnalyticsRoute: typeof AppPosAnalyticsRoute
  AppPosOrdersRoute: typeof AppPosOrdersRouteWithChildren
  AppPosIndexRoute: typeof AppPosIndexRoute
}

const AppPosRouteChildren: AppPosRouteChildren = {
  AppPosAnalyticsRoute: AppPosAnalyticsRoute,
  AppPosOrdersRoute: AppPosOrdersRouteWithChildren,
  AppPosIndexRoute: AppPosIndexRoute,
}

const AppPosRouteWithChildren =
  AppPosRoute._addFileChildren(AppPosRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsLeadRoutingRoute: typeof AppSettingsLeadRoutingRoute
  AppSettingsSocialRoute: typeof AppSettingsSocialRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsLeadRoutingRoute: AppSettingsLeadRoutingRoute,
  AppSettingsSocialRoute: AppSettingsSocialRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppWebinarsRouteChildren {
  AppWebinarsWebinarIdRoute: typeof AppWebinarsWebinarIdRoute
  AppWebinarsAnalyticsRoute: typeof AppWebinarsAnalyticsRoute
  AppWebinarsIndexRoute: typeof AppWebinarsIndexRoute
}

const AppWebinarsRouteChildren: AppWebinarsRouteChildren = {
  AppWebinarsWebinarIdRoute: AppWebinarsWebinarIdRoute,
  AppWebinarsAnalyticsRoute: AppWebinarsAnalyticsRoute,
  AppWebinarsIndexRoute: AppWebinarsIndexRoute,
}

const AppWebinarsRouteWithChildren = AppWebinarsRoute._addFileChildren(
  AppWebinarsRouteChildren,
)

interface AppRouteChildren {
  AppAcademyRoute: typeof AppAcademyRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRouteWithChildren
  AppFranchiseesRoute: typeof AppFranchiseesRouteWithChildren
  AppHrRoute: typeof AppHrRouteWithChildren
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppMyFranchiseRoute: typeof AppMyFranchiseRoute
  AppPosRoute: typeof AppPosRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSupportRoute: typeof AppSupportRoute
  AppTrainerRoute: typeof AppTrainerRoute
  AppWebinarsRoute: typeof AppWebinarsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademyRoute: AppAcademyRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRouteWithChildren,
  AppFranchiseesRoute: AppFranchiseesRouteWithChildren,
  AppHrRoute: AppHrRouteWithChildren,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppMyFranchiseRoute: AppMyFranchiseRoute,
  AppPosRoute: AppPosRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSupportRoute: AppSupportRoute,
  AppTrainerRoute: AppTrainerRoute,
  AppWebinarsRoute: AppWebinarsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  InvoiceTokenRoute: InvoiceTokenRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  WebinarSlugRoute: WebinarSlugRoute,
  ApiPublicSocialLeadHookRoute: ApiPublicSocialLeadHookRoute,
  ApiPublicWebinarRegisterHookRoute: ApiPublicWebinarRegisterHookRoute,
  ApiPublicWebinarRemindersRoute: ApiPublicWebinarRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
